function createfigure1(xdata1, ydata1, zdata1)
%CREATEFIGURE1(xdata1, ydata1, zdata1)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z

%  Auto-generated by MATLAB on 10-Nov-2020 13:09:52

% Create figure
figure1 = figure('WindowState','maximized');
colormap(jet(64));

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.123665686257189 0.111225490196078 0.737237744994783 0.815]);
hold(axes1,'on');

% Create contour
contour(xdata1,ydata1,zdata1,'LevelStep',1);

% Create ylabel
ylabel('Y(m)');

% Create xlabel
xlabel('X(m)');

% Create title
title('Stream function');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 20]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 10]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'BoxStyle','full','CLim',[10 80],'Color',[0 0 0],'Colormap',...
    [0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 0.9375;0.125 1 0.875;0.1875 1 0.8125;0.25 1 0.75;0.3125 1 0.6875;0.375 1 0.625;0.4375 1 0.5625;0.5 1 0.5;0.5625 1 0.4375;0.625 1 0.375;0.6875 1 0.3125;0.75 1 0.25;0.8125 1 0.1875;0.875 1 0.125;0.9375 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0;0.5 0 0],...
    'Layer','top');
% Create colorbar
colorbar(axes1);

